"""
FuguMT翻訳サーバー

リアルタイム翻訳専用AI WebSocketサーバー
FuguMTモデルを使用したオフライン翻訳システム

Author: Generated by AI Assistant
License: MIT
"""

__version__ = "1.0.0"
__author__ = "FuguMT Translation Server"

from .config import Config
from .translator import FuguMTTranslator
from .websocket_server import WebSocketServer

__all__ = [
    "Config",
    "FuguMTTranslator", 
    "WebSocketServer"
]